# Generated by Django 3.2.12 on 2022-02-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentNotes',
            new_name='AppointmentNote',
        ),
    ]
