# Generated by Django 3.2.12 on 2022-03-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment_core', '0003_rename_healthfacilityhours_healthfacilityhour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthfacility',
            options={'verbose_name_plural': 'Health Facilities'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='booked', max_length=12),
        ),
    ]
