# Generated by Django 3.2.12 on 2022-03-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment_core', '0004_auto_20220304_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('in-progress', 'In Progress'), ('closed', 'Closed')], default='booked', max_length=12),
        ),
    ]
